### ISSUE TITLE
Parallelizing CI job

### ISSUE THREAD

**Issue by HuStmpHrrr** [Beluga-lang/McLTT#82]
The current CI is single threaded. 

https://github.com/Beluga-lang/McLTT/blob/023acf26fc65642b7b424ede0c1aeefe73e3d146/.github/workflows/ci_build.yml#L55

we should make this `make` run with multiple threads.

https://github.com/SimenB/github-actions-cpu-cores

@Ailrun let me know if you have idea how to use this workflow.

**Comment by Ailrun** [comment]
It seems like we can just put
```yaml
      - name: Get number of CPU cores
        uses: SimenB/github-actions-cpu-cores@v2
        id: cpu-cores
```
step somewhere and then use `${{ steps.cpu-cores.outputs.count }}` later. In this case, we can put the above step before the step for `make` and then use `make -j ${{ steps.cpu-cores.outputs.count }}`.
